"""changelog: shown in What's new and copied into release.json. Newest first; add an entry with every release."""

CHANGELOG = [{'version': '2.8.2',
  'title': 'Smarter email sorting',
  'new': ['Cards in "Needs you" have a new ✕ button, "Not a job email": it hides the card and stops showing emails from that sender'],
  'fixed': ['Newsletters and adverts (for example "interview tips" or "practice test" emails) are no longer shown as interviews',
            "Emails in Gmail's Promotions and Social tabs are skipped, so checking email is quicker",
            'Older cards are sorted again once with the new rules, and wrong ones are removed',
            'Pasting a screenshot into Report a problem adds it only once']},
 {'version': '2.8.1',
  'title': 'Check email shows its progress',
  'new': ['While Check email runs, Home shows how many emails it has scanned and read, for example "Reading emails: 25 of 40"'],
  'fixed': ['The first email check is much quicker: job emails are downloaded in groups instead of one by one']},
 {'version': '2.8.0',
  'title': 'Quicker app, weekly summary and interview prep',
  'new': ['Home has a new "Your last 7 days" summary: applications sent, replies, interviews, offers, a weekly chart and a reminder when a job has had no reply for a week',
          'Find jobs warns you when you already applied to the same job through another link, and leaves it unticked',
          'Interview and test cards have a "Get ready" box with the date, a checklist and, with the AI helper on, prep tips written from your resume'],
  'fixed': ['The app opens pages faster: big forms and tables are only loaded when you open them, long job lists show 60 at a time, and saving is quicker']},
 {'version': '2.7.7',
  'title': 'More rejection emails found',
  'new': [],
  'fixed': ['Rejection emails worded without "unfortunately" (for example "decided not to", "not shortlisted", "moving ahead with other candidates") are now recognised, and older "received" cards are re-read once']},
 {'version': '2.7.6',
  'title': 'Company search and tidier boards',
  'new': ['Find jobs has a new tick box, "Show every opening at these companies": type a company and see all its current jobs',
          'The browser keeps your logins more reliably, and says so in the log if it cannot save them'],
  'fixed': ['In My jobs, the number at the top of the "Waiting for reply" column no longer spills outside its box',
            'If one saved login cookie is rejected, the rest are still restored']},
 {'version': '2.7.5',
  'title': 'Safer updates',
  'new': ['Updates are now checked against a signature from your helper before they install, so only genuine updates are accepted'],
  'fixed': ['The app window now only accepts commands from the app itself']},
 {'version': '2.7.4',
  'title': 'See what happened to your reports',
  'new': ['Settings has a new section, Your reports and ideas: everything you sent, with Open, Done or Not planned, and a link to read it'],
  'fixed': []},
 {'version': '2.7.3',
  'title': 'Opens maximised',
  'new': ['The Career Hub window now always opens maximised, filling the screen'],
  'fixed': []},
 {'version': '2.7.2',
  'title': 'Reports reach GitHub on a Mac',
  'new': [],
  'fixed': ['Report a problem and Suggest a feature could not reach GitHub on a Mac (a certificate error). They now connect properly']},
 {'version': '2.7.1',
  'title': 'Stay signed in',
  'new': ['LinkedIn and other sites you sign in to in the job window stay signed in after you close and reopen the app'],
  'fixed': ['The Chrome bar about an "unsupported command-line flag" no longer shows']},
 {'version': '2.7.0',
  'title': 'A fresher look',
  'new': ['A cleaner design: separate coloured cards on Home, a lighter calendar, softer shadows and a tidier side bar'],
  'fixed': ['On My jobs the stage filter no longer stretches across the whole page']},
 {'version': '2.6.21',
  'title': 'Sign-in fix',
  'new': [],
  'fixed': ['Google no longer says "This browser or app may not be secure" when you sign in to LinkedIn in the job window']},
 {'version': '2.6.20',
  'title': 'Clearer report messages',
  'new': [],
  'fixed': ['When a report or idea cannot be sent to GitHub, the message now says why (for example no token, or the token is missing a permission)']},
 {'version': '2.6.19',
  'title': 'Pictures in reports and ideas',
  'new': ['Report a problem and Suggest a feature let you add pictures: pick them or paste a screenshot with Ctrl+V'],
  'fixed': []},
 {'version': '2.6.18',
  'title': 'A sweeter hello',
  'new': ['The Home greeting uses a different pet name each hour',
          'A "Suggest a feature" button (side bar and Settings, Help) sends your idea to the person who looks after the app'],
  'fixed': ['Find jobs no longer shows older saved jobs that are outside the locations you want']},
 {'version': '2.6.17',
  'title': 'Rejection emails show again',
  'new': [],
  'fixed': ['Rejection (and other) emails that could not be matched to a job link were hidden when you had already applied to that company. They now show on that company card']},
 {'version': '2.6.16',
  'title': 'Waiting for reply and No response',
  'new': ['My jobs has a "Waiting for reply" column: an interview card moves there by itself once the interview date has passed',
          'My jobs has a "No response" column: jobs you applied to 30 or more days ago with no reply move there by itself'],
  'fixed': []},
 {'version': '2.6.15',
  'title': 'Each rejection gets its own card',
  'new': ['You can add a second and third job Gmail in Settings, and the app reads all of them',
          'Home shows a "See all emails" link, and the emails list shows 25 at a time with Show more'],
  'fixed': ['LinkedIn "Not selected" emails now show as separate cards in My jobs, with the right company and job title, instead of one "LinkedIn" card']},
 {'version': '2.6.14',
  'title': 'Only jobs where you can work',
  'new': [],
  'fixed': ['Find jobs no longer shows "remote" jobs tied to other countries, such as Germany remote or Remote in the US. Remote jobs open to India or anywhere still show']},
 {'version': '2.6.13',
  'title': 'Labelled and rejected mail read properly',
  'new': [],
  'fixed': ['Mail you labelled Rejected or Interviews is now sorted that way, including older mail and mail in sub-labels. Mail already in the app is re-sorted once',
            'An interview card shows the company (for example Accenture) instead of the name of the recruiter']},
 {'version': '2.6.12',
  'title': 'Select all and Unselect all',
  'new': ['Find jobs has Select all and Unselect all buttons. They work on the jobs you can see after filtering'],
  'fixed': ['Changing a filter no longer ticks every job again; the ones you unticked stay unticked']},
 {'version': '2.6.11',
  'title': 'Tidier job filters',
  'new': [],
  'fixed': ['The filters above the Find jobs results now sit in one neat row instead of four long boxes']},
 {'version': '2.6.10',
  'title': 'Your Gmail labels are used',
  'new': ['The app reads your Gmail labels: mail labelled Interviews, Rejected or Offer is sorted that way, and mail labelled Job boards is ignored'],
  'fixed': ['"You applied for 5 jobs" and review emails from Naukri, AmbitionBox and other job sites no longer show up as updates. Old ones are removed']},
 {'version': '2.6.9',
  'title': 'Updates keep working',
  'new': [],
  'fixed': ["After one update, the next update could fail to restart the app. The start file is now kept in the right format"]},
 {'version': '2.6.8',
  'title': 'Filters on your job lists',
  'new': ['Find jobs results can be filtered by job, company or city, how recently posted, and minimum match, and sorted by best match, newest or company',
          'The Apply list has a filter box',
          'My jobs: search now works on Emails, Accounts and Found, and a stage list narrows the Board and List'],
  'fixed': []},
 {'version': '2.6.7',
  'title': 'Fewer wrong interview emails',
  'new': ['New versions now download quietly in the background, so Update now finishes in a moment'],
  'fixed': ["Daily emails from Naukri, AmbitionBox and other job sites were wrongly shown as Interview. They are now ignored, and the ones already in your list are cleaned up"]},
 {'version': '2.6.6',
  'title': 'Experience in years and months',
  'new': [],
  'fixed': ["Boxes like Experience: Years and Months are now filled separately (3.5 years becomes 3 years and 6 months)",
            "More ways of asking when you joined your current company are understood, and dates like June 2023 work"]},
 {'version': '2.6.5',
  'title': 'Updates install again',
  'new': [],
  'fixed': ["Updating failed with a 'didn't download correctly' message. Updates now install normally"]},
 {'version': '2.6.4',
  'title': 'Links open in your own browser',
  'new': [],
  'fixed': ['Links to Gmail, job pages and other websites now open in your normal browser instead of a new tab inside the app window']},
 {'version': '2.6.3',
  'title': 'Calmer email check',
  'new': [],
  'fixed': ['The spinning circle for Check email now shows inside the Inbox box instead of over the whole page']},
 {'version': '2.6.2',
  'title': 'Reads more kinds of resumes',
  'new': [],
  'fixed': ['Work and education: "Read from my resume" now finds sections written in normal capitals (like Professional Experience) and jobs without a heading']},
 {'version': '2.6.1',
  'title': 'Updates in the side menu',
  'new': ['An Updates button at the bottom of the left menu checks for a new version, and shows a "new" tag when one is waiting'],
  'fixed': ['The update source is set automatically, so the empty box is gone from Settings']},
 {'version': '2.6',
  'title': 'Work history on Workday, and smarter interview dates',
  'new': ['Profile has a new Work and education section. "Read from my resume" fills it in for you to check',
          'On Workday applications the app now adds each job and degree from that section',
          'Interview times given in another time zone (for example EST or PST) are shown in your own time',
          'A reschedule email moves the interview on the calendar, and a cancellation removes it'],
  'fixed': ['Times written like 3:30 - 4:00pm are read as pm']},
 {'version': '2.5.1',
  'title': 'A shorter kind note',
  'new': [],
  'fixed': ['The note shown after many rejection emails is now just two short lines']},
 {'version': '2.5',
  'title': 'Calendar, to-do and a smarter inbox',
  'new': ['Home has a calendar for interviews and a to-do list',
          'The app reads your job Gmail when it opens and every hour, and puts interview dates from emails on the calendar',
          'Moving a card to Interview or Test asks for the date and adds it to the calendar',
          'My jobs now also shows companies that emailed you but were not applied to through the app',
          'A spinning circle shows while Check email works, and it tells you the result',
          'A kind note appears after more than 6 rejection emails'],
  'fixed': ['A card you moved by hand now follows a newer email (for example a rejection after an interview)',
            'The calendar and to-do update without reloading the whole Home page']},
 {'version': '2.4.1',
  'title': 'Fixes for forms, captcha and the icon',
  'new': ['A sharper "H" icon in the taskbar',
          'Before submitting, the app now reminds you to type a captcha in Chrome, and waits for you'],
  'fixed': ['Gender (and other dropdowns) now use your saved answer even when the website pre-selects something else',
            'Date of birth is now filled on websites with a calendar pop-up',
            'Upload boxes whose only text is a size note, like "10 MB max size", are no longer asked about']},
 {'version': '2.4',
  'title': 'Clearer look and better job search',
  'new': ['New default look: Clean white, with a charcoal side panel. Themes are now Clean white, Sand, Emerald, Slate and Mint',
          'Sharper, larger text and easier-to-read grey text',
          'Quick actions, Activity and Report a problem now sit under one More item in the sidebar',
          'Sharper "H" icon',
          'Find jobs: "Where should I search?" is explained in plain words, and searching the web now always checks a built-in list of companies that hire marketers',
          'Find jobs works from the job titles you type when no resume is found'],
  'fixed': ['Find jobs gave no answer when the resume was missing: it now says what to do',
            'Search the web found nothing because search engines blocked it',
            'Removed the duplicate "Paste a job link" bar from Home (use Apply), and the confusing dot and "1" in the sidebar']},
 {'version': '2.3',
  'title': 'Safer LinkedIn, Indeed and Naukri',
  'new': ['Paste LinkedIn, Indeed or Naukri links on Apply: the app keeps to a daily limit (default 10 per site) so your accounts stay safe',
          'The app waits a little between jobs on these sites, like a person would',
          'If a site asks you to prove you are human, the app waits for you and rests from that site if it keeps happening',
          'Job links in LinkedIn, Indeed and Naukri alert emails now appear in Find jobs',
          'New default look (Emerald: deep green with gold) plus new Peach and Mint themes; the other themes are still in Settings, Appearance',
          'A gold "H" icon for the app window in the taskbar'],
  'fixed': []},
 {'version': '2.2',
  'title': 'Smarter forms and automatic updates',
  'new': ['Updates install themselves from GitHub: checked at start, every hour, or with Check for updates',
          'All new questions on a page come together on one card, with AI drafts per question',
          'A small pop-up shows what was filled on each page',
          'Profile knows many more ways sites ask the same thing: experience, notice period, current location, '
          'location preference, company, job title, education',
          'New profile fields: gender, date of birth, current location, education, currently employed, key skills',
          'Eight colour themes in Settings, Appearance',
          'One job list on Apply: add links, apply to one, some or all; sent jobs leave the list',
          'Find jobs keeps every found job on the page and explains why jobs were skipped',
          "Install an update from a zip file if GitHub isn't set up"],
  'fixed': ['Windows launcher failed when the folder name had brackets',
            'Removed the --no-sandbox warning bar in Chrome',
            'Example text inside empty boxes was treated as a question',
            "The privacy / terms tick box wasn't ticked",
            'Captcha boxes are left for you instead of asked as a question',
            "Phone country code didn't match '+91'",
            'Clear message when Gmail needs an app password; automatic checks no longer pop up errors',
            "Sidebar didn't reach the bottom of the window",
            "Version 2.1 was listed twice in What's new"]},
 {'version': '2.1',
  'title': 'A fresh new look',
  'new': ['Redesigned app with a sidebar, a job-hunt funnel on Home and calmer, clearer screens',
          'My jobs is now a board: drag a card to change its stage, click it for emails and notes',
          "New Settings page: appearance, job email, logins, job search, AI helper, help, updates and what's new",
          'Quick actions: press ⌘K (Ctrl+K on Windows) to jump anywhere or run a command',
          'Pasted links turn into chips that show the job site, and you can save them for later in one click',
          'Find jobs shows a match ring for every result, with select-all and one-click apply or save',
          'Drop your resume onto Profile to add it',
          'Questions can be answered with the number keys',
          'A small celebration when an application is sent or an offer comes in',
          'Press 1 to 6 to switch pages'],
  'fixed': ['Unsaved changes are now clearly shown, with Save and Discard buttons']},
 {'version': '2.0',
  'title': 'Your own Career Hub',
  'new': ["Renamed to Harshitha's Career Hub, with a personal greeting on Home",
          "Everything personal now lives in one place: the “Harshitha's Data” folder with a single data file",
          'Your old data is moved in automatically (and a copy of the old files is kept in Backups)',
          'Dark mode: switch between Auto, Light and Dark with the button at the top',
          "This “What's new” list, shown once after every update",
          'Add resumes and cover letters from Profile → Files (no more copying files into folders)',
          '“Open in Excel / Numbers” now makes a fresh copy of the list each time'],
  'fixed': ['Profile settings can no longer get out of order when you clear and refill a box']},
 {'version': '1.2',
  'title': 'Email updates and a home screen',
  'new': ['Reads your job Gmail and sorts replies into interview, assessment, offer, rejection or received',
          'Home tab with your numbers and the emails that need your attention',
          'My jobs tab: every application with its stage, latest email and your notes',
          'Report a problem button: sends the log and screenshots to your helper',
          'Install updates from inside the app, with automatic backups first, plus a daily backup'],
  'fixed': ['Closing the app no longer waits on a slow email check',
            'Home cards no longer spill off the side of the window']},
 {'version': '1.1',
  'title': 'Smarter and safer',
  'new': ['Mac notification and sound when the app needs you',
          'Copy and Logs buttons for the activity panel',
          'Required boxes that are still empty are flagged before you submit',
          'Old written answers that mention another company are shown for review, not pasted',
          'Edit or delete remembered answers in Profile',
          'Checks for the “thank you” message after submitting',
          'Best-guess dropdown answers are highlighted in orange',
          'Label on the job window so you can tell the two Chrome windows apart',
          'Spots the same job opened through a different link',
          'Better date fields (e.g. “Immediately”, “15/11/2026”)',
          'Optional AI helper: drafts written answers and tailored cover letters',
          'Second and third resumes, chosen automatically by job title',
          'Daily automatic job search',
          'Windows support'],
  'fixed': ['The AI button no longer appears on date and link fields',
            'Submit confirmation now reads the application page, not the summary tab']},
 {'version': '1.0',
  'title': 'The app',
  'new': ['A proper app window with tabs instead of typing in Terminal',
          'Questions pop up as cards with buttons',
          'Profile form instead of editing a text file',
          'Tracker of applications, accounts and found jobs'],
  'fixed': []},
 {'version': '0.4',
  'title': 'Job finder',
  'new': ['Reads your resume and finds matching marketing jobs at companies you name or ones it discovers'],
  'fixed': []},
 {'version': '0.3',
  'title': 'Logins handled',
  'new': ['Clicks Apply, creates accounts and signs in by itself (Workday and others)',
          'One password for job sites, and a list of every account'],
  'fixed': []},
 {'version': '0.2',
  'title': 'Many jobs at once',
  'new': ['Apply to a whole list of links in one go',
          'Tracker of every application',
          'Marketing-focused profile',
          'Double-click setup, no typing'],
  'fixed': []},
 {'version': '0.1',
  'title': 'First version',
  'new': ['Fills application forms page by page, asks only new questions and remembers them',
          'Uploads your resume, clicks Next, stops before Submit with a summary'],
  'fixed': []}]
