"""changelog: shown in What's new and copied into release.json. Newest first; add an entry with every release."""

CHANGELOG = [{'version': '2.3',
  'title': 'Safer LinkedIn, Indeed and Naukri',
  'new': ['Paste LinkedIn, Indeed or Naukri links on Apply: the app keeps to a daily limit (default 10 per site) so your accounts stay safe',
          'The app waits a little between jobs on these sites, like a person would',
          'If a site asks you to prove you are human, the app waits for you and rests from that site if it keeps happening',
          'Job links in LinkedIn, Indeed and Naukri alert emails now appear in Find jobs',
          'New default look (Emerald: deep green with gold) plus new Peach and Mint themes; the other themes are still in Settings, Appearance',
          'A gold "H" icon for the app window in the taskbar'],
  'fixed': []},
 {'version': '2.2',
  'title': 'Smarter forms and automatic updates',
  'new': ['Updates install themselves from GitHub: checked at start, every hour, or with Check for updates',
          'All new questions on a page come together on one card, with AI drafts per question',
          'A small pop-up shows what was filled on each page',
          'Profile knows many more ways sites ask the same thing: experience, notice period, current location, '
          'location preference, company, job title, education',
          'New profile fields: gender, date of birth, current location, education, currently employed, key skills',
          'Eight colour themes in Settings, Appearance',
          'One job list on Apply: add links, apply to one, some or all; sent jobs leave the list',
          'Find jobs keeps every found job on the page and explains why jobs were skipped',
          "Install an update from a zip file if GitHub isn't set up"],
  'fixed': ['Windows launcher failed when the folder name had brackets',
            'Removed the --no-sandbox warning bar in Chrome',
            'Example text inside empty boxes was treated as a question',
            "The privacy / terms tick box wasn't ticked",
            'Captcha boxes are left for you instead of asked as a question',
            "Phone country code didn't match '+91'",
            'Clear message when Gmail needs an app password; automatic checks no longer pop up errors',
            "Sidebar didn't reach the bottom of the window",
            "Version 2.1 was listed twice in What's new"]},
 {'version': '2.1',
  'title': 'A fresh new look',
  'new': ['Redesigned app with a sidebar, a job-hunt funnel on Home and calmer, clearer screens',
          'My jobs is now a board: drag a card to change its stage, click it for emails and notes',
          "New Settings page: appearance, job email, logins, job search, AI helper, help, updates and what's new",
          'Quick actions: press ⌘K (Ctrl+K on Windows) to jump anywhere or run a command',
          'Pasted links turn into chips that show the job site, and you can save them for later in one click',
          'Find jobs shows a match ring for every result, with select-all and one-click apply or save',
          'Drop your resume onto Profile to add it',
          'Questions can be answered with the number keys',
          'A small celebration when an application is sent or an offer comes in',
          'Press 1 to 6 to switch pages'],
  'fixed': ['Unsaved changes are now clearly shown, with Save and Discard buttons']},
 {'version': '2.0',
  'title': 'Your own Career Hub',
  'new': ["Renamed to Harshitha's Career Hub, with a personal greeting on Home",
          "Everything personal now lives in one place: the “Harshitha's Data” folder with a single data file",
          'Your old data is moved in automatically (and a copy of the old files is kept in Backups)',
          'Dark mode: switch between Auto, Light and Dark with the button at the top',
          "This “What's new” list, shown once after every update",
          'Add resumes and cover letters from Profile → Files (no more copying files into folders)',
          '“Open in Excel / Numbers” now makes a fresh copy of the list each time'],
  'fixed': ['Profile settings can no longer get out of order when you clear and refill a box']},
 {'version': '1.2',
  'title': 'Email updates and a home screen',
  'new': ['Reads your job Gmail and sorts replies into interview, assessment, offer, rejection or received',
          'Home tab with your numbers and the emails that need your attention',
          'My jobs tab: every application with its stage, latest email and your notes',
          'Report a problem button: sends the log and screenshots to your helper',
          'Install updates from inside the app, with automatic backups first, plus a daily backup'],
  'fixed': ['Closing the app no longer waits on a slow email check',
            'Home cards no longer spill off the side of the window']},
 {'version': '1.1',
  'title': 'Smarter and safer',
  'new': ['Mac notification and sound when the app needs you',
          'Copy and Logs buttons for the activity panel',
          'Required boxes that are still empty are flagged before you submit',
          'Old written answers that mention another company are shown for review, not pasted',
          'Edit or delete remembered answers in Profile',
          'Checks for the “thank you” message after submitting',
          'Best-guess dropdown answers are highlighted in orange',
          'Label on the job window so you can tell the two Chrome windows apart',
          'Spots the same job opened through a different link',
          'Better date fields (e.g. “Immediately”, “15/11/2026”)',
          'Optional AI helper: drafts written answers and tailored cover letters',
          'Second and third resumes, chosen automatically by job title',
          'Daily automatic job search',
          'Windows support'],
  'fixed': ['The AI button no longer appears on date and link fields',
            'Submit confirmation now reads the application page, not the summary tab']},
 {'version': '1.0',
  'title': 'The app',
  'new': ['A proper app window with tabs instead of typing in Terminal',
          'Questions pop up as cards with buttons',
          'Profile form instead of editing a text file',
          'Tracker of applications, accounts and found jobs'],
  'fixed': []},
 {'version': '0.4',
  'title': 'Job finder',
  'new': ['Reads your resume and finds matching marketing jobs at companies you name or ones it discovers'],
  'fixed': []},
 {'version': '0.3',
  'title': 'Logins handled',
  'new': ['Clicks Apply, creates accounts and signs in by itself (Workday and others)',
          'One password for job sites, and a list of every account'],
  'fixed': []},
 {'version': '0.2',
  'title': 'Many jobs at once',
  'new': ['Apply to a whole list of links in one go',
          'Tracker of every application',
          'Marketing-focused profile',
          'Double-click setup, no typing'],
  'fixed': []},
 {'version': '0.1',
  'title': 'First version',
  'new': ['Fills application forms page by page, asks only new questions and remembers them',
          'Uploads your resume, clicks Next, stops before Submit with a summary'],
  'fixed': []}]
